import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import FooterSection from "@/components/footer";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:any) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Navbar />
        {children}
        <FooterSection/>
      </body>
    </html>
  );
}
